# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  displayName: "Build and Publish Container"
  inputs:
    containerRegistry: '25570031-2ce7-4597-a91c-138aa2180235'
    repository: 'cloudbootcamp-austin'
    command: 'buildAndPush'
    tags: '$(Build.BuildId), latest'

- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'Visual Studio Enterprise(23d8c84a-ad22-409f-8fe6-d81e2439b47a)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az container restart -g rg-cloudbootcampaustin -n cloudbootcampaustinweb'
  displayName: "Reset ACI"